# Generated by Django 5.0.1 on 2025-04-21 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dosage_unit', models.CharField(choices=[('mg', 'Milligrams'), ('g', 'Grams'), ('ml', 'Milliliters'), ('pill', 'Pill(s)'), ('tab', 'Tablet(s)'), ('cap', 'Capsule(s)')], default='mg', max_length=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('as_needed', 'As Needed')], default='daily', max_length=10)),
                ('days_of_week', models.CharField(blank=True, help_text='Comma separated days: 1-7 (Monday-Sunday)', max_length=20, null=True)),
                ('date_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Day of month for monthly reminders', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='reminders.medication')),
            ],
        ),
    ]
